'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getView: () => ipcRenderer.invoke('view:get'),
  greet: () => ipcRenderer.invoke('npc:greet'),
  daily: () => ipcRenderer.invoke('npc:daily'),
  poke: () => ipcRenderer.invoke('npc:poke'),
  chat: (text) => ipcRenderer.invoke('npc:chat', text),
  confirmProposal: (id, keep) => ipcRenderer.invoke('npc:confirm', id, keep),
  cancelProposal: () => ipcRenderer.invoke('npc:cancel'),
  checkStatus: () => ipcRenderer.invoke('npc:status'),
  toggleAI: () => ipcRenderer.send('ai:toggle'),
  touch: () => ipcRenderer.send('npc:touch'),
  setObjective: (qid, idx, done) => ipcRenderer.invoke('quest:objective', qid, idx, done),
  submit: (qid, report) => ipcRenderer.invoke('quest:submit', qid, report),
  setActive: (qid) => ipcRenderer.invoke('quest:active', qid),
  toggleDaily: (rowId, done) => ipcRenderer.invoke('daily:toggle', rowId, done),
  chooseBranch: (date, which) => ipcRenderer.invoke('daily:branch', date, which),
  dailyReport: (fields) => ipcRenderer.invoke('daily:report', fields),
  addQuest: (f) => ipcRenderer.invoke('plan:addQuest', f),
  editQuest: (id, f) => ipcRenderer.invoke('plan:editQuest', id, f),
  deleteQuest: (id) => ipcRenderer.invoke('plan:deleteQuest', id),
  addObjective: (id, text) => ipcRenderer.invoke('plan:addObjective', id, text),
  deleteObjective: (id, i) => ipcRenderer.invoke('plan:deleteObjective', id, i),
  addRow: (date, f) => ipcRenderer.invoke('plan:addRow', date, f),
  deleteRow: (rowId) => ipcRenderer.invoke('plan:deleteRow', rowId),
  addReminder: (f) => ipcRenderer.invoke('plan:addReminder', f),
  deleteReminder: (id) => ipcRenderer.invoke('plan:deleteReminder', id),
  importIcs: () => ipcRenderer.invoke('ics:import'),
  exportIcs: () => ipcRenderer.invoke('ics:export'),
  setSmart: (on) => ipcRenderer.invoke('smart:set', on),
  startFocus: (min) => ipcRenderer.invoke('focus:start', min),
  cancelFocus: () => ipcRenderer.invoke('focus:cancel'),
  focusPeek: () => ipcRenderer.invoke('focus:peek'),
  drawFortune: () => ipcRenderer.invoke('fortune:draw'),
  divineInfo: () => ipcRenderer.invoke('divine:info'),
  divineCheck: (q) => ipcRenderer.invoke('divine:check', q),
  divineCast: (opts) => ipcRenderer.invoke('divine:cast', opts),
  divineRead: (id) => ipcRenderer.invoke('divine:read', id),
  shopOpen: () => ipcRenderer.invoke('shop:open'),
  shopGift: (id) => ipcRenderer.invoke('shop:gift', id),
  shopBuy: (id) => ipcRenderer.invoke('shop:buy', id),
  shopEquip: (slot, id) => ipcRenderer.invoke('shop:equip', slot, id || null),
  shopDraw: (n, ticket) => ipcRenderer.invoke('shop:draw', n, !!ticket),
  shopWish: (id) => ipcRenderer.invoke('shop:wish', id),
  twinsTake: () => ipcRenderer.invoke('twins:take'),
  shopExchange: (id) => ipcRenderer.invoke('shop:exchange', id),
  collectionOpen: () => ipcRenderer.invoke('collection:open'),
  setHud: (on) => ipcRenderer.invoke('ui:setHud', !!on),
  journalOpen: (key, quiet) => ipcRenderer.invoke('journal:open', key || null, !!quiet),
  journalComment: (key, force) => ipcRenderer.invoke('journal:comment', key || null, !!force),
  journalExport: (key) => ipcRenderer.invoke('journal:export', key || null),
  journalCopy: (text) => ipcRenderer.invoke('journal:copy', text),
  notebookPeek: (quiet) => ipcRenderer.invoke('notebook:peek', !!quiet),
  notebookForget: (id) => ipcRenderer.invoke('notebook:forget', id),
  notebookClear: () => ipcRenderer.invoke('notebook:clear'),
  setNotebook: (on) => ipcRenderer.invoke('notebook:set', on),
  // 🎓 新手引導
  setupProbe: () => ipcRenderer.invoke('setup:probe'),
  setupPull: (model) => ipcRenderer.invoke('setup:pull', model),
  setupCancelPull: (model) => ipcRenderer.invoke('setup:cancelPull', model),
  setupOpenOllama: () => ipcRenderer.invoke('setup:openOllama'),
  setupInstallOllama: () => ipcRenderer.invoke('setup:installOllama'),
  setupCancelInstall: () => ipcRenderer.invoke('setup:cancelInstall'),
  setupSetModel: (model) => ipcRenderer.invoke('setup:setModel', model),
  setupCreatePlan: (f) => ipcRenderer.invoke('setup:createPlan', f),
  setupSamplePlan: () => ipcRenderer.invoke('setup:samplePlan'),
  setupChoosePlan: () => ipcRenderer.invoke('setup:choosePlan'),
  setupImportIcs: () => ipcRenderer.invoke('setup:importIcs'),
  setupSchedule: (f) => ipcRenderer.invoke('setup:schedule', f),
  setupFinish: () => ipcRenderer.invoke('setup:finish'),
  setupRestart: () => ipcRenderer.invoke('setup:restart'),
  hideTutorial: () => ipcRenderer.invoke('tutorial:hide'),
  // 🩺 健康檢查
  healthCheck: () => ipcRenderer.invoke('health:check'),
  healthFix: (action) => ipcRenderer.invoke('health:fix', action),
  setIgnoreMouse: (ignore) => ipcRenderer.send('win:ignore', ignore),
  moveWindow: (dx, dy) => ipcRenderer.send('win:move', { dx, dy }),
  dragEnd: () => ipcRenderer.send('win:dragEnd'),
  openMenu: () => ipcRenderer.send('win:menu'),
  setMini: (on) => ipcRenderer.send('win:mini', on),
  on: (channel, fn) => {
    const allowed = ['view:update', 'npc:lines', 'ui:open', 'ui:mini', 'ui:shrink', 'ui:focus', 'ui:fortune', 'fx:reward', 'setup:progress', 'setup:ollama', 'presence', 'cursor'];
    if (!allowed.includes(channel)) return;
    ipcRenderer.on(channel, (_e, payload) => fn(payload));
  },
});
